스터디 도메인, API 추가 수정 반영
code-beacon-lab/cbl-api pull request #11
Opened 2023-03-14 14:40 UTC by Kormap

1.  요청 Request -> ResonseDto 반환
2. import 문 정리 (optimization)
3. 빈칸, 불필요한 코드 정리
4. 카멜케이스 전환
5. List 조회 시 빈값일 경우 반환값 (확인 시 나은 방법이 있을 경우 조언 부탁드립니다)

2023-03-19 05:12 UTC, dahyeong-yun requested changes
일단 반영에 큰 무리가 없을 것 같은데 application.yml 파일 때문에 동작 오류가 있어 머지는 안될 것 같습니다. 해당 부분 확인 부탁드려요!

2023-03-19 05:12 UTC, dahyeong-yun commented on src/main/resources/application.yml
해당 파일이 삭제되면 안될 것 같네요.=

2023-03-19 05:12 UTC, dahyeong-yun commented on src/test/java/org/api/beacon/studyTest/StudyRepositoryTest.java
> +
불필요한 공백은 삭제해주세요.

2023-03-19 05:12 UTC, dahyeong-yun commented on src/test/java/org/api/beacon/studyTest/StudyRepositoryTest.java
> +        System.out.println("getStudy="+getStudy.get().getName());
시스템 콘솔 사용은 마스터에 머지할 코드는 아닌 것 같습니다.

2023-03-19 05:12 UTC, dahyeong-yun commented on src/test/java/org/api/beacon/studyTest/StudyRepositoryTest.java
> +@SpringBootTest
application.yml 삭제 이 후에 해당 테스트가 정상적으로  pass 되나요?

2023-03-19 05:12 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/study/interfaces/StudyResponseDto.java
> +    public StudyResponseDto(Study study) {
Study 객체로 StudyResponse 객체를 만들고 싶을 때는 정적 팩토리 메서드를 사용하는 것도 좋아 보입니다.

2023-03-19 05:12 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/study/interfaces/StudyApiController.java
> +        //TODO Object 타입 반환 방법이 아닌 다른 방식이 있을지 고민
서비스 메소드가 리스트 타입을 반환하고 있으므로 리스트 타입을 반환하면 되지 않을까요?

2023-03-19 05:12 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/study/interfaces/StudyApiController.java
> +        if(studyService.retrieveStudies(regId).isEmpty()) return ResponseEntity.badRequest().body("해당 ID : " + regId + " 로 등록된 스터디가 없습니다.");
응답 케이스 구분에 따라서 ResponseEntity 빌트인 메소드 사용한 것은 매우 좋은 것 같습니다 👍🏼

2023-03-20 13:10 UTC, Kormap commented
application.yml 살리고 PR 예정

2023-03-20 13:10 UTC, closed without merging