FEAT(Reply): 도메인 생성 및 API(CRU) 생성
code-beacon-lab/cbl-api pull request #9
Opened 2023-03-12 14:35 UTC by ByeonSeongUk

- Reply 도메인 생성
- 댓글 작성 기능 추가
- 게시물에 대한 모든 댓글 조회 기능 추가
- 댓글에 대한 수정 기능 추가

2023-03-12 23:19 UTC, dahyeong-yun requested changes
내용 확인 한 번 부탁 드립니다.

2023-03-12 23:19 UTC, dahyeong-yun commented on README.md
>  ## 설계
설계사항 공유 좋습니다 👍🏼 👍🏼 👍🏼

2023-03-12 23:19 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/reply/application/impl/ReplyServiceImpl.java
> +        replyOrigin.updateReply(
DTO를 만든 이 후에 굳이 다시 getter로 필드별로 파라미터를 만들 필요가 있을까요?

2023-03-12 23:19 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/reply/domain/Reply.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
생성자의 접근 제한을 둔 이유가 있을까요? 기본 생성자는 접근 제한이 public인 상태인데 현재 라인과 구분되는 이유가 있는지 궁금합니다.

2023-03-12 23:19 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/reply/domain/Reply.java
> +                .id(replyRequestDto.getId())
id값을 클라이언트에서 받아 오는 걸로 지정한다면, identical 하게 아이디 설정을 한 것과 배치되는 것 같습니다. reply_id를 어디서 만들고 싶은지 결정을 해야할 것 같아요

2023-03-12 23:19 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/reply/infrastructure/store/ReplyStoreImpl.java
> +    private void vaildate(Reply reply) {
이하 validation용 2가지 메서드를 어디서 사용하는 것일까요?

2023-03-12 23:19 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/reply/interfaces/ReplyApiController.java
> +    @PutMapping
댓글을 수정하는 경우에는 메세지 바디로 댓글 아이디를 찾고, 조회하는 경우에는 URI 경로로 댓글 아이디를 받고 있는데 차이가 있는 이유가 있을까요?

2023-03-12 23:19 UTC, dahyeong-yun commented on src/main/java/org/api/beacon/reply/application/impl/ReplyServiceImpl.java
> +    @Transactional
트랜잭션을 거는 메서드와 아닌 것의 차이가 무엇인지? 서비스 클래스에 기본적으로 트랜잭션을 걸 수는 없는지?

2023-03-17 06:44 UTC, ByeonSeongUk commented on src/main/java/org/api/beacon/reply/domain/Reply.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
이 부분은 feature/CBL-34 에 Member 도메인을 보고 따라 했었는데 접근 제한을 거는 이유를 찾아보겠습니다.

2023-03-17 06:45 UTC, ByeonSeongUk commented on src/main/java/org/api/beacon/reply/infrastructure/store/ReplyStoreImpl.java
> +    private void vaildate(Reply reply) {
해당 부분은 삭제를 안하고 PR을 날렸습니다 ㅠㅠ 다음번 PR때 수정 후 날리겠습니다.

2023-03-17 07:21 UTC, ByeonSeongUk commented on src/main/java/org/api/beacon/reply/domain/Reply.java
> +                .id(replyRequestDto.getId())
이 부분은 생각없이 작업했던 것 같습니다 ㅠㅠ id 값은 지우겠습니다!

2023-03-17 07:23 UTC, ByeonSeongUk commented on README.md
>  ## 설계
피드백 감사합니다 ㅎㅎ 최대한 이해하며 개발해보려 했는데 아직도 따라치고 기능이 돌아가게끔 하는데 중점을 두고 작업을 했던 것 같습니다. 피드백 주신 사항 수정하며 이해하도록 노력하겠습니다!

2023-03-20 11:35 UTC, dahyeong-yun commented
@ByeonSeongUk 작업 진행 상황이 어떻게 될까요

2023-03-20 13:56 UTC, ByeonSeongUk commented
> @ByeonSeongUk 작업 진행 상황이 어떻게 될까요

저번주 개인일정이 많아서 작업을 많이 못했습니다... 이번주 주말내로 피드백 주신 사항과 타임리프 적용까지 완료해두겠습니다.

2023-03-29 11:28 UTC, dahyeong-yun commented
제목에 개발한 이슈 번호 기재 하셔서 재 요청 부탁드립니다~

2023-03-29 11:28 UTC, closed without merging